owner: DeschutesDesignGroupLLC
repo: PERSCOM-3.0-Status

sites:
  - name: PERSCOM
    url: https://perscom.io

assignees:
  - JonErickson

status-website:
  cname: status.perscom.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PERSCOM System Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
