owner: DeschutesDesignGroupLLC
repo: System-Status-Monitor

sites:
  - name: Website
    url: https://www.deschutesdesigngroup.com
  - name: Community Forums
    url: https://community.deschutesdesigngroup.com
  - name: Support Desk
    url: https://support.deschutesdesigngroup.com/hc/en-us
  - name: Client Control Panel
    url: https://solutions.deschutesdesigngroup.com
  - name: Authentication Services
    url: https://solutions.deschutesdesigngroup.com

assignees:
  - JonErickson

status-website:
  cname: status.deschutesdesigngroup.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Deschutes Design Group LLC System Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
